# Day 1 - PyTorch Tensor & Autograd

# 1. Tensor Basics

> Source: D2L §2.1

In [3]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [8]:
x.numel()

12

In [9]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
torch.zeros((2,3,4))
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(3,4)

tensor([[ 0.6664, -0.5310,  1.4773, -0.5023],
        [-0.8225, -0.6695,  1.4905, -0.1921],
        [-0.7233,  1.2106,  0.7655,  2.6986]])

In [14]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [18]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y),dim = 0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [19]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
X.sum()

tensor(66.)

In [21]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [22]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1442418541584
id(Z): 1442418541584


In [24]:
before = id(X)
X += Y
id(X) == before

True

# 2. Data Preprocessing

> Source: D2L §2.2

In [25]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [33]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [34]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [35]:
inputs = pd.get_dummies(inputs, dummy_na=False)
print(inputs)

   NumRooms  Alley_Pave
0       3.0        True
1       2.0       False
2       4.0       False
3       3.0       False


In [36]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1.],
         [2., 0.],
         [4., 0.],
         [3., 0.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [37]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'NumRooms': [3, 2, np.nan, 4, 3],
    'Alley':    [np.nan, np.nan, 'Pave', np.nan, np.nan],
    'Area':     [80, 90, 100, np.nan, 120],
    'Price':    [120000, 130000, 150000, 170000, 160000]
})

print(data)

   NumRooms Alley   Area   Price
0       3.0   NaN   80.0  120000
1       2.0   NaN   90.0  130000
2       NaN  Pave  100.0  150000
3       4.0   NaN    NaN  170000
4       3.0   NaN  120.0  160000


In [38]:
data.isna().sum()

NumRooms    1
Alley       4
Area        1
Price       0
dtype: int64

In [40]:
most_missing_col = data.isna().sum().idxmax()

data = data.drop(columns=[most_missing_col])

print(data)

   NumRooms   Area   Price
0       3.0   80.0  120000
1       2.0   90.0  130000
2       NaN  100.0  150000
3       4.0    NaN  170000
4       3.0  120.0  160000


In [46]:
data = data.fillna(data.mean(numeric_only=True))
X = torch.tensor(
    data.to_numpy(dtype=float),
    dtype = torch.float32
)

print(X)
print(X.shape)
print(X.dtype)

tensor([[3.0000e+00, 8.0000e+01, 1.2000e+05],
        [2.0000e+00, 9.0000e+01, 1.3000e+05],
        [3.0000e+00, 1.0000e+02, 1.5000e+05],
        [4.0000e+00, 9.7500e+01, 1.7000e+05],
        [3.0000e+00, 1.2000e+02, 1.6000e+05]])
torch.Size([5, 3])
torch.float32


# 3. Linear Algebra Essentials

> Source: D2L §2.3

In [47]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [51]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [53]:
A_sum_axis0 = A.sum(axis = 0)
A_sum_axis0 , A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [54]:
A_sum_axis1 = A.sum(axis = 1)
A_sum_axis1 , A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [55]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [56]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [58]:
A.shape, x.shape, torch.mv(A, x), A @ x

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [59]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [60]:
torch.abs(u).sum()

tensor(7.)

In [61]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

# 4. Calculus Intuition

> Source: D2L §2.4

# 5. Automatic Differentiation

> Source: D2L §2.5

In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)  # 等价于x=torch.arange(4.0,requires_grad=True)
x.grad  # 默认值是None

In [3]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [7]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
# 本例只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [9]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True])

In [11]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [12]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [13]:
a.grad == d / a

tensor(True)

In [16]:
x = torch.tensor(2., requires_grad=True)

y = x ** 2
u = y.detach()

print(y.requires_grad)
print(y.grad_fn)

print(u.requires_grad)
print(u.grad_fn)

True
False
None


In [19]:
x = torch.tensor(3., requires_grad=True)
y = x ** 2
z = y * 5
u = y.detach()

print("x:", x, x.requires_grad, x.grad_fn)
print("y:", y, y.requires_grad, y.grad_fn)
print("z:", z, z.requires_grad, z.grad_fn)
print("u:", u, u.requires_grad, u.grad_fn)

v = u * 10

print(v)
print(v.requires_grad)
print(v.grad_fn)

x: tensor(3., requires_grad=True) True None
y: tensor(9., grad_fn=<PowBackward0>) True <PowBackward0 object at 0x000001D83EBF87C0>
z: tensor(45., grad_fn=<MulBackward0>) True <MulBackward0 object at 0x000001D83EBF8700>
u: tensor(9.) False None
tensor(90.)
False
None


In [20]:
print(x.shape, x.ndim, x.numel())
print(y.shape, y.ndim, y.numel())
print(z.shape, z.ndim, z.numel())

torch.Size([]) 0 1
torch.Size([]) 0 1
torch.Size([]) 0 1


# 6. Probability Basics

> Source: D2L §2.6

In [21]:
%matplotlib inline
import torch
from torch.distributions import multinomial

In [22]:
fair_probs = torch.ones([6]) / 6
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 1., 0., 0., 0., 0.])

In [23]:
multinomial.Multinomial(10, fair_probs).sample()

tensor([2., 2., 1., 0., 2., 3.])

# 7. PyTorch Documentation / API Lookup

> Source: D2L §2.7

In [24]:
import torch

print(dir(torch.distributions))

['AbsTransform', 'AffineTransform', 'Bernoulli', 'Beta', 'Binomial', 'CatTransform', 'Categorical', 'Cauchy', 'Chi2', 'ComposeTransform', 'ContinuousBernoulli', 'CorrCholeskyTransform', 'CumulativeDistributionTransform', 'Dirichlet', 'Distribution', 'ExpTransform', 'Exponential', 'ExponentialFamily', 'FisherSnedecor', 'Gamma', 'GeneralizedPareto', 'Geometric', 'Gumbel', 'HalfCauchy', 'HalfNormal', 'Independent', 'IndependentTransform', 'InverseGamma', 'Kumaraswamy', 'LKJCholesky', 'Laplace', 'LogNormal', 'LogisticNormal', 'LowRankMultivariateNormal', 'LowerCholeskyTransform', 'MixtureSameFamily', 'Multinomial', 'MultivariateNormal', 'NegativeBinomial', 'Normal', 'OneHotCategorical', 'OneHotCategoricalStraightThrough', 'Pareto', 'Poisson', 'PositiveDefiniteTransform', 'PowerTransform', 'RelaxedBernoulli', 'RelaxedOneHotCategorical', 'ReshapeTransform', 'SigmoidTransform', 'SoftmaxTransform', 'SoftplusTransform', 'StackTransform', 'StickBreakingTransform', 'StudentT', 'TanhTransform', 'T

In [25]:
help(torch.ones)

Help on built-in function ones in module torch:

ones(...)
    ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with the scalar value `1`, with the shape defined
    by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
    
    Keyword arguments:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, us

# 8. Day 1 Summary

In [26]:
import torch

x = torch.tensor([1., 2., 3.], requires_grad=True)

y = x ** 2
z = y * 3

loss = z.sum()

loss.backward()

print(x.grad)

tensor([ 6., 12., 18.])


In [27]:
x.grad.zero_()

y = x ** 2
u = y.detach()
z = u * x

loss = z.sum()
loss.backward()

print(x.grad)

tensor([1., 4., 9.])


# Day 1：PyTorch Tensor & Autograd

## 1. `requires_grad`

```python
x = torch.tensor(3., requires_grad=True)
```

- `requires_grad=True`：告诉 PyTorch **追踪与该 Tensor 有关的梯度计算**。
- 后续由 `x` 参与的可微运算会自动构建计算图。

---

## 2. `grad_fn`

`grad_fn` 记录这个 Tensor **由什么运算产生**。

```python
x = torch.tensor(3., requires_grad=True)
y = x ** 2

x.grad_fn  # None
y.grad_fn  # PowBackward
```

- `x.grad_fn = None`：`x` 是叶子 Tensor，本身不是通过其他运算产生的。
- `y.grad_fn = PowBackward`：`y` 是通过 `x ** 2` 得到的。

---

## 3. `backward()` 与 `.grad`

```python
loss.backward()
```

从 `loss` 出发，沿计算图进行**反向传播**，计算 loss 对相关变量的梯度。

```python
x.grad
```

表示：

`∂loss / ∂x`

深度学习中通常把最终目标变成一个**标量 loss**，然后调用：

```python
loss.backward()
```

---

## 4. 梯度清零

PyTorch 的梯度默认会**累加**，所以训练时通常需要：

```python
optimizer.zero_grad()
loss.backward()
optimizer.step()
```

流程：

```text
清梯度 → 计算 loss → backward → 得到梯度 → 更新参数
```

---

## 5. `detach()` 与 `torch.no_grad()`

### `detach()`

```python
u = y.detach()
```

切断**某个 Tensor** 与之前计算图之间的梯度关系。

### `torch.no_grad()`

```python
with torch.no_grad():
    y = x ** 2
```

让整个代码块中的运算**不记录梯度**。

记忆：

```text
detach()  → 切 Tensor
no_grad() → 关掉一段代码的梯度记录
```

---

## 6. Autograd 完整流程

```text
requires_grad=True
        ↓
Forward
        ↓
构建计算图
        ↓
得到 scalar loss
        ↓
loss.backward()
        ↓
计算梯度
        ↓
parameter.grad
        ↓
optimizer.step()
        ↓
更新参数
```

## 一句话总结

> **Forward 计算预测和 loss，Backward 计算 loss 对参数的梯度，Optimizer 根据梯度更新参数。**